CREATE SCHEMA IF NOT EXISTS materializacion_operaciones;

SET search_path TO materializacion_operaciones, public;

CREATE TABLE IF NOT EXISTS proveedores (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    rfc TEXT NOT NULL UNIQUE,
    tipo TEXT NOT NULL,
    nivel INTEGER NOT NULL,
    banco TEXT,
    cuenta TEXT,
    clabe TEXT,
    repse BOOLEAN NOT NULL DEFAULT FALSE,
    tiene_fisico BOOLEAN NOT NULL DEFAULT FALSE,
    efos_ok BOOLEAN NOT NULL DEFAULT TRUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    nombre TEXT NOT NULL,
    rol TEXT NOT NULL,
    password TEXT NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS empresas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    rfc TEXT NOT NULL UNIQUE,
    tipo_empresa TEXT NOT NULL DEFAULT 'servicios',
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    onboarding_status TEXT NOT NULL DEFAULT 'borrador',
    onboarding_aprobada_en TIMESTAMP WITHOUT TIME ZONE,
    onboarding_aprobada_por TEXT,
    reglas_negocio JSONB NOT NULL DEFAULT '{}'::jsonb,
    creado_en TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS empresa_documentos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
    tipo TEXT NOT NULL,
    nombre_archivo TEXT,
    url TEXT,
    estado_validacion TEXT NOT NULL DEFAULT 'pendiente',
    observaciones TEXT,
    vigente_hasta DATE,
    subido_por TEXT,
    validado_por TEXT,
    subido_en TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    validado_en TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS empresa_cuentas_bancarias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
    banco TEXT NOT NULL,
    titular TEXT NOT NULL,
    clabe TEXT NOT NULL,
    numero_cuenta TEXT,
    moneda TEXT NOT NULL DEFAULT 'MXN',
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    validada BOOLEAN NOT NULL DEFAULT FALSE,
    validada_por TEXT,
    validada_en TIMESTAMP WITHOUT TIME ZONE,
    creada_en TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizada_en TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS folios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero TEXT NOT NULL UNIQUE,
    proveedor_id INTEGER NOT NULL REFERENCES proveedores(id) ON DELETE CASCADE,
    empresa_id INTEGER REFERENCES empresas(id) ON DELETE CASCADE,
    presupuesto DOUBLE PRECISION NOT NULL,
    periodo TEXT NOT NULL,
    fecha_limite_entrega DATE,
    estado TEXT NOT NULL DEFAULT 'activo',
    creado_en TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cerrado_en TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS expedientes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folio_id INTEGER NOT NULL UNIQUE REFERENCES folios(id) ON DELETE CASCADE,
    completitud DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    pago_bloqueado BOOLEAN NOT NULL DEFAULT TRUE,
    razon_negocio TEXT,
    manifiesto BOOLEAN NOT NULL DEFAULT FALSE,
    creado_en TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS documentos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expediente_id INTEGER NOT NULL REFERENCES expedientes(id) ON DELETE CASCADE,
    tipo TEXT NOT NULL,
    nombre_archivo TEXT,
    url TEXT,
    subido BOOLEAN NOT NULL DEFAULT FALSE,
    subido_en TIMESTAMP WITHOUT TIME ZONE,
    subido_por TEXT,
    validacion_estado TEXT NOT NULL DEFAULT 'pendiente',
    validacion_detalle TEXT,
    validado_en TIMESTAMP WITHOUT TIME ZONE,
    validado_por TEXT
);

CREATE TABLE IF NOT EXISTS traspasos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folio_id INTEGER NOT NULL REFERENCES folios(id) ON DELETE CASCADE,
    folio_bancario TEXT,
    banco_origen TEXT NOT NULL,
    banco_destino TEXT,
    cuenta_destino TEXT,
    monto DOUBLE PRECISION NOT NULL,
    fecha TEXT NOT NULL,
    estado TEXT NOT NULL DEFAULT 'pendiente',
    excede_presup BOOLEAN NOT NULL DEFAULT FALSE,
    diferencia DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    registrado_por TEXT,
    creado_en TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabla TEXT NOT NULL,
    tabla_id INTEGER NOT NULL,
    accion TEXT NOT NULL,
    detalle TEXT,
    usuario TEXT,
    creado_en TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS efos_registro (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rfc TEXT NOT NULL UNIQUE,
    publicado_en_sat BOOLEAN NOT NULL DEFAULT TRUE,
    fuente TEXT NOT NULL DEFAULT 'sat',
    actualizado_en TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alertas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo TEXT NOT NULL,
    severidad TEXT NOT NULL DEFAULT 'amarillo',
    mensaje TEXT NOT NULL,
    estado TEXT NOT NULL DEFAULT 'activa',
    origen TEXT NOT NULL DEFAULT 'auto',
    proveedor_id INTEGER REFERENCES proveedores(id),
    empresa_id INTEGER REFERENCES empresas(id),
    folio_id INTEGER REFERENCES folios(id),
    expediente_id INTEGER REFERENCES expedientes(id),
    periodo TEXT,
    creado_en TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS policy_sets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL UNIQUE REFERENCES empresas(id) ON DELETE CASCADE,
    nombre TEXT NOT NULL DEFAULT 'Politica Operativa',
    activa_version_id INTEGER,
    creado_en TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS policy_versions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_set_id INTEGER NOT NULL REFERENCES policy_sets(id) ON DELETE CASCADE,
    version INTEGER NOT NULL,
    estado TEXT NOT NULL DEFAULT 'draft',
    parametros JSONB NOT NULL DEFAULT '{}'::jsonb,
    creado_por TEXT,
    nota_cambio TEXT,
    creado_en TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    publicado_en TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT uq_policy_version UNIQUE (policy_set_id, version)
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'policy_sets_activa_version_id_fkey'
    ) THEN
        ALTER TABLE policy_sets
            ADD CONSTRAINT policy_sets_activa_version_id_fkey
            FOREIGN KEY (activa_version_id) REFERENCES policy_versions(id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS policy_evaluations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_version_id INTEGER REFERENCES policy_versions(id),
    empresa_id INTEGER REFERENCES empresas(id),
    proveedor_id INTEGER REFERENCES proveedores(id),
    expediente_id INTEGER REFERENCES expedientes(id),
    tipo TEXT NOT NULL DEFAULT 'clasificacion',
    input_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    output_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    creado_en TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS empresa_credenciales (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INTEGER NOT NULL UNIQUE REFERENCES empresas(id) ON DELETE CASCADE,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS proveedor_credenciales (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id INTEGER NOT NULL REFERENCES proveedores(id) ON DELETE CASCADE,
    empresa_id INTEGER NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_proveedor_empresa_credencial UNIQUE (proveedor_id, empresa_id)
);

CREATE INDEX IF NOT EXISTS idx_empresa_documentos_empresa_id ON empresa_documentos (empresa_id);
CREATE INDEX IF NOT EXISTS idx_empresa_cuentas_bancarias_empresa_id ON empresa_cuentas_bancarias (empresa_id);
CREATE INDEX IF NOT EXISTS idx_folios_proveedor_id ON folios (proveedor_id);
CREATE INDEX IF NOT EXISTS idx_folios_empresa_id ON folios (empresa_id);
CREATE INDEX IF NOT EXISTS idx_documentos_expediente_id ON documentos (expediente_id);
CREATE INDEX IF NOT EXISTS idx_traspasos_folio_id ON traspasos (folio_id);
CREATE INDEX IF NOT EXISTS idx_alertas_proveedor_id ON alertas (proveedor_id);
CREATE INDEX IF NOT EXISTS idx_alertas_empresa_id ON alertas (empresa_id);
CREATE INDEX IF NOT EXISTS idx_alertas_folio_id ON alertas (folio_id);
CREATE INDEX IF NOT EXISTS idx_alertas_expediente_id ON alertas (expediente_id);
CREATE INDEX IF NOT EXISTS idx_policy_versions_policy_set_id ON policy_versions (policy_set_id);
CREATE INDEX IF NOT EXISTS idx_policy_evaluations_policy_version_id ON policy_evaluations (policy_version_id);
CREATE INDEX IF NOT EXISTS idx_policy_evaluations_empresa_id ON policy_evaluations (empresa_id);
CREATE INDEX IF NOT EXISTS idx_policy_evaluations_proveedor_id ON policy_evaluations (proveedor_id);
CREATE INDEX IF NOT EXISTS idx_policy_evaluations_expediente_id ON policy_evaluations (expediente_id);
CREATE INDEX IF NOT EXISTS idx_proveedor_credenciales_proveedor_id ON proveedor_credenciales (proveedor_id);
CREATE INDEX IF NOT EXISTS idx_proveedor_credenciales_empresa_id ON proveedor_credenciales (empresa_id);
