LEVEL_LABELS = {
    1: "Transaccional",
    2: "Operativo",
    3: "Servicios Intangibles",
    4: "Estratégico",
}

LEVEL_RISK = {
    1: "bajo",
    2: "medio",
    3: "alto",
    4: "critico",
}

DOCS_BY_LEVEL = {
    1: [
        "cfdi_xml",
        "cfdi_pdf",
        "constancia_sat",
        "nota_remision",
        "foto_entrega",
        "crp",
    ],
    2: [
        "cfdi_xml",
        "cfdi_pdf",
        "constancia_sat",
        "foto_entrega",
        "crp",
        "opinion_32d",
        "contrato_nom151",
        "carta_porte",
        "certificado_calidad",
        "entrada_erp",
    ],
    3: [
        "cfdi_xml",
        "cfdi_pdf",
        "constancia_sat",
        "crp",
        "opinion_32d",
        "contrato_nom151",
        "repse",
        "curriculum_empresa",
        "bitacora",
        "minutas",
        "correos_avance",
        "entregable_efirma",
        "manifiesto_materialidad",
        "cuestionario_5a",
    ],
    4: [
        "cfdi_xml",
        "cfdi_pdf",
        "constancia_sat",
        "crp",
        "opinion_32d",
        "contrato_nom151",
        "repse",
        "bitacora",
        "minutas",
        "entregable_efirma",
        "manifiesto_materialidad",
        "acta_constitutiva",
        "poder_representante",
        "declaracion_anual",
        "nomina_imss",
        "seguro_rc",
        "cedula_activos",
        "cuestionario_5a",
    ],
}

DOC_LABELS = {
    "cfdi_xml": "CFDI XML",
    "cfdi_pdf": "CFDI PDF",
    "constancia_sat": "Constancia SAT",
    "nota_remision": "Nota de remisión",
    "foto_entrega": "Foto de entrega",
    "crp": "Complemento de recepción de pagos",
    "opinion_32d": "Opinión 32-D",
    "contrato_nom151": "Contrato NOM-151",
    "carta_porte": "Carta porte",
    "certificado_calidad": "Certificado de calidad",
    "entrada_erp": "Entrada ERP",
    "repse": "Registro REPSE",
    "curriculum_empresa": "Currículum empresarial",
    "bitacora": "Bitácora",
    "minutas": "Minutas",
    "correos_avance": "Correos de avance",
    "entregable_efirma": "Entregable con e.firma",
    "manifiesto_materialidad": "Manifiesto materialidad",
    "acta_constitutiva": "Acta constitutiva",
    "poder_representante": "Poder representante",
    "declaracion_anual": "Declaración anual",
    "nomina_imss": "Nómina IMSS",
    "seguro_rc": "Seguro RC",
    "cedula_activos": "Cédula activos",
    "cuestionario_5a": "Cuestionario 5-A",
}
